app/models/models.py
from .. import db


# Create a User model
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(100), nullable=False)
    username = db.Column(db.String(100), nullable=False)
    password = db.Column(db.String(100), nullable=False)

    def __repr__(self):
        return f"User('{self.name}', '{self.email}')"
    
# Create a Category Model
class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    products = db.relationship('Product', backref='category', lazy=True)

# Create a Product Model
class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    price = db.Column(db.Float, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    
    db.init_app(app)

    from .routes.index_routes import index as index_blueprint
    app.register_blueprint(index_blueprint)

    from .routes.auth_routes import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    
    from .routes.user_routes import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .routes.category_routes import category as category_blueprint
    app.register_blueprint(category_blueprint)

    from .routes.product_routes import product as product_blueprint
    app.register_blueprint(product_blueprint)

    with app.app_context():
        db.create_all()
        return app

app/routes/auth_routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from app.models.models import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Get the form data
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()
        # Check if user exists and password matches
        if user and user.password == password:
            session['username'] = username
            flash('Login successful', 'success')
            return redirect(url_for('main.index'))
        else:
            flash('Invalid username or password', 'danger')
            return redirect(url_for('auth.login'))
    return render_template('auth/login.html')

@auth.route('/logout')
def logout():
    session.pop('username', None)
    flash('You have been logged out', 'info')
    return redirect(url_for('index.home'))

app/routes/category_routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from app.models.models import Category
from app.decorators import login_required
from .. import db

category = Blueprint('category', __name__)

@category.route('/categories', methods=['GET'])
@login_required
def index():
    categories = Category.query.all()
    return render_template('categories/index.html', categories=categories)

@category.route('/categories/create', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        name = request.form.get('name')
        new_category = Category(name=name)
        db.session.add(new_category)
        db.session.commit()
        flash('Category created successfully')
        return redirect(url_for('category.index'))
    return render_template('categories/create.html')


@category.route('/category/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    cat = Category.query.get_or_404(id)
    if request.method == 'POST':
        cat.name = request.form.get('name')
        
        db.session.commit()
        flash('Category updated successfully')
        return redirect(url_for('category.index'))
    return render_template('categories/edit.html', cat=cat)

@category.route('/category/delete/<int:id>')
@login_required
def delete(id):
    cat = Category.query.get(id)
    if not cat:
        flash('Category not found')
        return redirect(url_for('category.index'))
    db.session.delete(cat)
    db.session.commit()
    flash('Category deleted successfully')
    return redirect(url_for('category.index'))

app/routes/index_routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

index = Blueprint('index', __name__)

@index.route('/')
def flask():
    return render_template('index/flask.html')

@index.route('/home')
def home():
    return render_template('index/home.html')

@index.route('/about')
def about():
    return render_template('index/about.html')

app/routes/product_routes.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from app.models.models import Product, Category
from app.decorators import login_required
from .. import db

product = Blueprint('product', __name__)

@product.route('/products', methods=['GET'])
@login_required
def index():
    products = Product.query.all()
    return render_template('products/index.html', products=products)

@product.route('/products/create', methods=['GET', 'POST'])
@login_required
def create():
    categories = Category.query.all()
    if request.method == 'POST':
        name = request.form.get('name')
        price = request.form.get('price')
        category_id = request.form.get('category_id')
        new_product = Product(name=name, price=float(price), category_id=int(category_id))
        db.session.add(new_product)
        db.session.commit()
        flash('Product created successfully')
        return redirect(url_for('product.index'))
    return render_template('products/create.html', categories=categories)


@product.route('/product/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    prod = Product.query.get_or_404(id)
    if request.method == 'POST':
        prod.name = request.form.get('name')
        prod.price = request.form.get('price')
        prod.category_id = request.form.get('category_id')
    
        db.session.commit()
        flash('Product updated successfully')
        return redirect(url_for('product.index'))
    return render_template('products/edit.html', prod=prod)

@product.route('/product/delete/<int:id>')
@login_required
def delete(id):
    prod = Product.query.get(id)
    if not prod:
        flash('Product not found')
        return redirect(url_for('product.index'))
    db.session.delete(prod)
    db.session.commit()
    flash('Product deleted successfully')
    return redirect(url_for('product.index'))

app/routes/user_routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from app.models.models import User
from app.decorators import login_required
from .. import db

main = Blueprint('main', __name__)

@main.route('/user')
@login_required
def index():
    users = User.query.all()
    return render_template('user/index.html', users=users)

@main.route('/user/create', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        new_user = User(name=name, email=email, username=username, password=password)
        db.session.add(new_user)
        db.session.commit()
        flash('User created successfully')
        return redirect(url_for('main.index'))
    return render_template('user/create.html')

@main.route('/user/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    user = User.query.get_or_404(id)
    if request.method == 'POST':
        user.name = request.form.get('name')
        user.email = request.form.get('email')
        db.session.commit()
        flash('User updated successfully')
        return redirect(url_for('main.index'))
    return render_template('user/edit.html', user=user)

@main.route('/user/delete/<int:id>')
@login_required
def delete(id):
    user = User.query.get(id)
    if not user:
        flash('User not found')
        return redirect(url_for('main.index'))
    db.session.delete(user)
    db.session.commit()
    flash('User deleted successfully')
    return redirect(url_for('main.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="bg-warning">

    <nav class="navbar navbar-expand-lg bg-primary">

        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('index.flask')}}">My Flask Project</a>

            <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>
            </button> -->
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('index.home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('index.about')}}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.index')}}">Manage Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('category.index')}}">Manage Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('product.index')}}">Manage Products</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <!-- Show username from session -->

                    {% if session.get('username') %}
                    <span class="form-control me-2">Welcome, {{ session.get('username') }}</span>
                    <a href="{{ url_for('auth.logout')}}" class="btn btn-outline-danger">Logout</a>
                    {% else %}
                    <a href="{{ url_for('auth.login')}}" class="btn btn-outline-success" style="color:aliceblue; background-color: rgb(28, 118, 4);" >Login</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </nav>

    <!-- Main Content Start Here -->
    <div class="container my-5">
        <div class="p-5 text-center bg-body-tertiary rounded-3">

            <p class="col-lg-8 mx-auto fs-5 text-muted">
            <div>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <span>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </span>
                {% endif %}
                {% endwith %}
            </div>
            </p>
            <div>
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    <!-- Main Content End Here -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Add New Category</h1>
<br />
<br />
<form action="{{ url_for('category.create') }}" method="post">
    <!-- <div class="form-group row">
        <label for="id" class="col-sm-2 col-form-label">Id</label>
        <div class="col-sm-10">
            <input type="text" name="id" id="id" class="form-control" />
        </div>
    </div>
    <br /> -->
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-1">
            <button type="submit" class="btn btn-primary">Create</button> |
            <a href="{{ url_for('category.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
    <br />
</form>

{% endblock %}

app/templates/categories/edit.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Edit Existing Category</h1>
<br />
<form action="{{ url_for('category.edit', id=cat.id) }}" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" value="{{ cat.name }}" class="form-control" />
        </div>
    </div>

    <br />
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-1">
            <button type="submit" class="btn btn-primary">Edit</button> |
            <a href="{{ url_for('category.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

{% endblock %}

app/templates/categories/index.html
{% extends 'base.html' %}

{% block content %}

<br />

<!-- Link for Create Category -->
<a href="{{ url_for('category.create') }}" class="btn btn-primary">Create Category</a>
<br>
<br>

<h2>Categories List</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for category in categories %}
        <tr>
            <td>{{ category.id }}</td>
            <td>{{ category.name }}</td>
            <td>
                <a href="{{ url_for('category.edit', id=category.id) }}" class="btn btn-primary">Edit</a>
                <a href="{{ url_for('category.delete', id=category.id) }}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
</table>
{% endblock %}


      
   

app/templates/index/about.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Welcome to the About Page</h1>

{% endblock %}

app/templates/index/flask.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Welcome to My Falsk Project</h1>

{% endblock %}

app/templates/index/home.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Welcome to the Home Page</h1>

{% endblock %}

app/templates/products/create.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Add New Product</h1>
<br /><br />
<form action="{{ url_for('product.create') }}" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" class="form-control" />
        </div>
    </div>
    <br />
    
    <div class="form-group row">
        <label for="price" class="col-sm-2 col-form-label">Price</label>
        <div class="col-sm-10">
            <input type="number" name="price" id="price" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label for="category" class="col-sm-2 col-form-label">Category</label>
        <div class="col-sm-10">
            <select name="category_id" id="category_id" class="form-control">
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <br /><br />
        <div class="form-group row">
            <div class="col-sm-10 offset-sm-1">
                <button type="submit" class="btn btn-primary">Create</button> |
                <a href="{{ url_for('category.index') }}" class="btn btn-secondary">Cancel</a>
            </div>
        </div>
        <br />
</form>

{% endblock %}

app/templates/products/edit.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Edit Existing Product</h1>
<br />
<form action="{{ url_for('product.edit', id=prod.id) }}" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" value="{{ prod.name }}" class="form-control" />
        </div>
    </div>
    <br>

    <div class="form-group row">
        <label for="price" class="col-sm-2 col-form-label">Price</label>
        <div class="col-sm-10">
            <input type="number" name="price" id="price" value="{{ prod.price }}" class="form-control" />
        </div>
    </div>
    <br>

    <div class="form-group row">
        <label for="category_id" class="col-sm-2 col-form-label">Category_id</label>
        <div class="col-sm-10">
            <input type="text" name="category_id" id="category_id" value="{{ prod.category_id }}" class="form-control" />
        </div>
    </div>
    <br>

    <br />
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-1">
            <button type="submit" class="btn btn-primary">Edit</button> |
            <a href="{{ url_for('product.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

{% endblock %}

app/templates/products/index.html
{% extends 'base.html' %}

{% block content %}

<br />

<!-- Link for Create Category -->
<a href="{{ url_for('product.create') }}" class="btn btn-primary">Create Product</a>
<br>
<br>

<h2>Product List</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
            <th>Category_name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ product.id }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.category_id }}</td>
            <td>
                <a href="{{ url_for('product.edit', id=product.id) }}" class="btn btn-primary">Edit</a>
                <a href="{{ url_for('product.delete', id=product.id) }}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}


app/templates/user/create.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Add New User</h1>
<br />
<form action="{{ url_for('main.create') }}" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            <input type="email" name="email" id="email" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label for="username" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
            <input type="text" name="username" id="username" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
            <input type="password" name="password" id="password" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-1">
            <button type="submit" class="btn btn-primary">Create</button> |
            <a href="{{ url_for('main.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
    <br />
</form>

{% endblock %}

app/templates/user/edit.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Edit Existing User</h1>
<br />
<form action="{{ url_for('main.edit', id=user.id) }}" method="post">
    <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="name" id="name" value="{{ user.name }}" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            <input type="email" name="email" id="email" value="{{ user.email }}" class="form-control" />
        </div>
    </div>
    <br />
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-1">
            <button type="submit" class="btn btn-primary">Edit</button> |
            <a href="{{ url_for('main.index') }}" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</form>

{% endblock %}

app/templates/user/index.html
{% extends 'base.html' %}

{% block content %}

<!-- Create User Link -->
<div class="text-right">
    <a href="{{ url_for('main.create') }}" class="btn btn-primary">Create User</a>
</div>

<br />

<h2>Users List</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>
                <a href="{{ url_for('main.edit', id=user.id) }}" class="btn btn-primary">Edit</a>
                <a href="{{ url_for('main.delete', id=user.id) }}" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

    {% endblock %}